[package]
name = "dfe"
version = "0.1.3"
edition = "2021"
description = "DFE - Documentos Fiscais Eletrônicos Brasileiros"
license = "MIT"
readme = "README.md"
keywords = ["rust", "nfe", "dfe"]
categories = ["api-bindings", "parsing"]
homepage = "https://github.com/GustavoOta/dfe"
repository = "https://github.com/GustavoOta/dfe"

[dependencies]
openssl = { version = "0.10", features = ["vendored"] }
reqwest = "0.12.9"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.41.1", features = ["full"] }
